=== raml-apis/Twilio/schemas/media-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "sid" : {
      "type" : "string" ,
      "required" : false
    } ,
    "account_sid" : {
      "type" : "string" ,
      "required" : false
    } ,
    "parent_sid" : {
      "type" : "string" ,
      "required" : false
    } ,
    "content-type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "date_created" : {
      "type" : "string" ,
      "required" : false
    } ,
    "date_updated" : {
      "type" : "string" ,
      "required" : false
    } ,
    "uri" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Twilio/examples/media-example.json
{
        "sid": "ME557ce644e5ab84fa21cc21112e22c485",
        "account_sid": "ACda6f1e11047ebd6fe7a55f120be3a900",
        "parent_sid": "MM8ff928b2451c0db925bd2d581f0fba79",
        "content-type": "image/jpeg",
        "date_created": "Fri, 26 Apr 2013 05:41:35 +0000",
        "date_updated": "Fri, 26 Apr 2013 05:41:35 +0000",
        "uri": "/2010-04-01/Accounts/ACda6f1e11047ebd6fe7a55f120be3a900/Message/SM8dfedb55c129dd4d6bd1f59af9d11080/Media/ME557ce644e5ab84fa21cc21112e22c485.json"
    }
