=== raml-apis/Twilio/schemas/message-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "account_sid" : {
      "type" : "string" ,
      "required" : false
    } ,
    "api_version" : {
      "type" : "string" ,
      "required" : false
    } ,
    "body" : {
      "type" : "string" ,
      "required" : false
    } ,
    "num_segments" : {
      "type" : "string" ,
      "required" : false
    } ,
    "num_media" : {
      "type" : "string" ,
      "required" : false
    } ,
    "date_created" : {
      "type" : "string" ,
      "required" : false
    } ,
    "date_sent" : {
      "type" : "string" ,
      "required" : false
    } ,
    "date_updated" : {
      "type" : "string" ,
      "required" : false
    } ,
    "direction" : {
      "type" : "string" ,
      "required" : false
    } ,
    "from" : {
      "type" : "string" ,
      "required" : false
    } ,
    "price" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sid" : {
      "type" : "string" ,
      "required" : false
    } ,
    "status" : {
      "type" : "string" ,
      "required" : false
    } ,
    "to" : {
      "type" : "string" ,
      "required" : false
    } ,
    "uri" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Twilio/examples/message-example.json
{
  "account_sid" : "AC5ef8732a3c49700934481addd5ce1659" ,
  "api_version" : "2010-04-01" ,
  "body" : "Hey Jenny why aren't you returning my calls?" ,
  "num_segments" : "1" ,
  "num_media" : "0" ,
  "date_created" : "Mon, 16 Aug 2010 03:45:01 +0000" ,
  "date_sent" : "Mon, 16 Aug 2010 03:45:03 +0000" ,
  "date_updated" : "Mon, 16 Aug 2010 03:45:03 +0000" ,
  "direction" : "outbound-api" ,
  "from" : "+14158141829" ,
  "price" : "-0.02000" ,
  "sid" : "MM800f449d0399ed014aae2bcc0cc2f2ec" ,
  "status" : "sent" ,
  "to" : "+15558675309" ,
  "uri" : "/2010-04-01/Accounts/AC5ef872f6da5a21de157d80997a64bd33/Messages/MM800f449d0399ed014aae2bcc0cc2f2ec.json"
}
